[project]
name = "resume-job-matching"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.4.0",
    "pandas>=2.3.3",
]
